//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dl
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public decimal id { get; set; }
        public decimal apartmentId { get; set; }
        public decimal consumerId { get; set; }
        public System.DateTime arrivalTime { get; set; }
        public System.DateTime departureTime { get; set; }
    
        public virtual consumer consumer { get; set; }
        public virtual vacationApartment vacationApartment { get; set; }
    }
}
