//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dl
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacationApartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vacationApartment()
        {
            this.order = new HashSet<order>();
        }
    
        public decimal id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> homeownerId { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public decimal houseNumber { get; set; }
        public string neighborhood { get; set; }
        public string postalCode { get; set; }
        public Nullable<decimal> floor { get; set; }
        public Nullable<decimal> lan { get; set; }
        public Nullable<decimal> lng { get; set; }
        public Nullable<decimal> amountOfRooms { get; set; }
        public decimal beds { get; set; }
        public Nullable<bool> aSynagogueNearby { get; set; }
        public Nullable<bool> eruvAnTheNeighborhood { get; set; }
        public Nullable<bool> yard { get; set; }
        public Nullable<bool> pool { get; set; }
        public Nullable<bool> jacuzzi { get; set; }
        public Nullable<decimal> weekendPrice { get; set; }
        public Nullable<decimal> pricePerNight { get; set; }
        public Nullable<decimal> priceForSaturdayNight { get; set; }
        public string moreDetails { get; set; }
        public string img { get; set; }
    
        public virtual homeowner homeowner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
    }
}
